version: "3"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    expose:
      - 8080
    volumes:
      - ./backend:/app/backend

  scheduler:
    build: ./scheduler
    container_name: flask-apscheduler
    restart: always
    expose:
      - 8081
    volumes:
      - ./scheduler:/app/scheduler


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "8787:5432"