version: "3"

services:
  redis:
    build: ./conf
    container_name: crypto-schedule-redis
    restart: always
    expose:
      - 6379

  backend:
    build: ./backend
    container_name: crypto-schedule-backend
    restart: always
    expose:
      - 8080
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      - redis

  worker:
    build: ./backend
    command: celery -A celery_worker.celery worker --loglevel=info -B
    volumes:
      - ./backend:/app
      - ./logs/celery/:/app/logs/
    links:
        - redis

  nginx:
    image: nginx
    container_name: crypto-schedule-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./logs/:/var/log/nginx/
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend