version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    expose:
      - 8080
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  scheduler:
    build: ./scheduler
    container_name: flask-apscheduler
    restart: always
    expose:
      - 8081
    volumes:
      - ./scheduler:/app/scheduler